# Welcome to Jekyll v4.0.0!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author:
  name: ganekuro
  email: ganekuro@mailo.com
title: GARNET CROW unofficial website
subtitle: ガーネットクロウ アンオフィシャルサイト
description: > # this means to ignore newlines until "message:"
  Welcome to the GARNET CROW unofficial website!

# Page urls
message:     "/message.html"
live:        "/message/live.html"
profile:     "/profile.html"
discography: "/discography.html"
lyrics:      "/lyrics.html"
diary:       "/diary.html"
staff:       "/garnetcrow10th.html"
photos:      "/photos.html"
history:     "/history.html"

# Where things are
source      : .
destination : ./_site
layouts_dir : _layouts
includes_dir: _includes
sass:
    sass_dir: _sass

# Handling Reading
exclude     : ["LICENSE", "README.md"]
encoding    : "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md" # no spaces between exts

# Filtering Content
limit_posts: 0
future     : false

# Conversion
markdown         : kramdown
highlighter      : rouge
excerpt_separator: "\n\n"
incremental      : false

# Serving
port: 4000
host: 127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink: date # /:categories/:year/:month/:day/:title:output_ext
timezone : Asia/Shanghai
